### ISSUE TITLE
detected?

### ISSUE THREAD

**Issue by cartiace0d** [Real-Ascarre/Apex-Legends-Esp#4]
is this detected right outta the bat? sd

**Comment by Real-Ascarre** [comment]
Usermode is UD but Driver needs some rework

**Comment by Real-Ascarre** [comment]
Can u be specific on what errors you are getting

**Comment by cartiace0d** [comment]
i compiled everything but the esp isn't working for some reason

**Comment by cartiace0d** [comment]
do you have discord?

**Comment by Real-Ascarre** [comment]
First Switch to Windowed or Boderless Mode then test. Download required files.
Message me on telegram if u want - 
UserName - Ascarre
